AUTHORS
=======
Chris Jackson wrote the original bash script.

Even Nedberg, Savvas Radevic, and Frank Gerbig wrote the current python implementation.

Nicolas Iselin, Savvas Radevic, and Frank Gerbig wrote the manpages.


SEE ALSO
========

**timekpr(8)**, **timekpr.conf(5)**, **timekpr-gui(8)**, **timekpr-gui3(8)**, **timekpr-client(8)**, The **Linux-PAM guide for system administrators** (modules **access** and **limits**).
